name: Sync AD and Turn into a Dev Version

# Controls when the workflow will run
on:
  schedule:
    - cron: '52 4 * * 1'
  workflow_dispatch: # on button click


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner:  AppDaemon
          merge_method: rebase
