name: Sync AD and Turn into a Dev Version

# Controls when the workflow will run
on:
  schedule:
    - cron: '52 4 * * 1'
  workflow_dispatch: # on button click


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    name: Sync repo to Upstream AppDaemon/appdaemon
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: AppDaemon/appdaemon
          source_branch: "*"
          destination_branch: "*"
          github_token: ${{ secrets.PAT }}
          sync_tags: "true"
  
  dockerbasemodify_dev:
    name: Modify Docker Base Image Tag dev
    needs: sync
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'dev'

      - run: |
          mkdir -p ~/tmp
          git clone https://github.com/blindlight86/useful-scripts.git ~/tmp
          cp ~/tmp/ad_debug.py debug.py
          mkdir -p .vscode
          cp -r ~/tmp/.vscode/launch.json .vscode/launch.json
          chmod 777 ~/tmp/filemodify.sh
          sh ~/tmp/filemodify.sh
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Change Docker Base Image" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'dev'

  push_to_registry_dev:
    needs: dockerbasemodify_dev
    name: Push Docker image tag dev to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'dev'

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: blindlight/appdaemon
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: blindlight/appdaemon:dev
          labels: ${{ steps.meta.outputs.labels }}
          
  dockerbasemodify_master:
    name: Modify Docker Base Image Tag master
    needs: sync
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'

      - run: |
          mkdir -p ~/tmp
          git clone https://github.com/blindlight86/useful-scripts.git ~/tmp
          cp ~/tmp/ad_debug.py debug.py
          mkdir -p .vscode
          cp -r ~/tmp/.vscode/launch.json .vscode/launch.json
          chmod 777 ~/tmp/filemodify.sh
          sh ~/tmp/filemodify.sh
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Change Docker Base Image" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'master'

  push_to_registry_master:
    name: Push Docker image master dev to Docker Hub
    needs: dockerbasemodify_master
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: 'master'

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: blindlight/appdaemon
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: blindlight/appdaemon:latest
          labels: ${{ steps.meta.outputs.labels }}
          
